### ISSUE TITLE
Allow passing parameters for `pkcs11_eventmgr` through the main `pam_pkcs11` class

### ISSUE THREAD

**Issue by mlegner** [siemens/puppet-pam_pkcs11#16]
The `pam_pkcs11` class supports enabling `pkcs11_eventmgr` through the `manage_pkcs11_eventmgr` parameter. However, it is not possible to parametrize `pkcs11_eventmgr` further except by instantiating it directly.

We could simply disallow directly instantiating `pkcs11_eventmgr` and instead add all the class parameters from `pkcs11_eventmgr` to the main `pam_pkcs11` class and inherit it from there.

**Comment by cmhe** [comment]
Hmm.. I assumed that those parameters are passed as hiera values... I thought that this is how it is done in puppet... Why is that not possible or wanted?

**Comment by mlegner** [comment]
I agree that this would probably be the best way to use this module. For now, we simply instantiate the classes separately, which isn't a huge problem.

Closing this.
