### ISSUE TITLE
Nightly tests fail for various distributions with Puppet 6

### ISSUE THREAD

**Issue by mlegner** [siemens/puppet-pam_pkcs11#20]
The nightly tests fail for CentOS, OracleLinux, and Scientific with Puppet 6 due to an error during the agent install, see https://github.com/siemens/puppet-pam_pkcs11/actions/runs/2982566003.

**Comment by cmhe** [comment]
That seems to be an issue somewhere upstream with puppetlabs&co.

**Comment by mlegner** [comment]
Probably just an intermittent issue; seems to be resolved now.
